apiVersion: accounts.nats.io/v1alpha1
kind: SigningKey
metadata:
  labels:
    app.kubernetes.io/name: signingkey
    app.kubernetes.io/instance: signingkey-sample
    app.kubernetes.io/part-of: nats-accounts-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nats-accounts-operator
  name: signingkey-sample
spec:
  # TODO(user): Add fields here
