## Append samples you want in your CSV to this file as resources ##
resources:
- _v1alpha1_operator.yaml
- _v1alpha1_account.yaml
- _v1alpha1_user.yaml
- _v1alpha1_signingkey.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
